services:

    #services:

    Oihso\TelegramBotApiBundle\Service\Bot:
        arguments: ['@service_container']

    # commands:

    Oihso\TelegramBotApiBundle\Command\WebhookSetCommand:
        arguments: ['@Oihso\TelegramBotApiBundle\Service\Bot']
        tags:
            - { name: console.command }

    Oihso\TelegramBotApiBundle\Command\WebhookDeleteCommand:
        arguments: ['@Oihso\TelegramBotApiBundle\Service\Bot']
        tags:
            - { name: console.command }

    Oihso\TelegramBotApiBundle\Command\WebhookInfoCommand:
        arguments: ['@Oihso\TelegramBotApiBundle\Service\Bot']
        tags:
            - { name: console.command }

